name: C/C++ CI

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - '**'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake python3 python3-dev python3-pip xsltproc tidy

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    
    - name: Build HTML Tidy
      run: |
        git clone https://github.com/htacg/tidy-html5.git /tmp/tidy-html5
        cd /tmp/tidy-html5
        cd build/cmake
        cmake ../.. -DCMAKE_BUILD_TYPE=Release [-DCMAKE_INSTALL_PREFIX=/path/for/install]        
        make
        sudo make install

    - name: Configure with CMake
      run: |
        mkdir -p pythml/build
        cd pythml/build
        cmake ..

    - name: Build with Make
      run: |
        cd pythml/build
        make

    - name: Run Tests
      run: |
        cd pythml/build
        ./pythml ../test/cases/base.html
