name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake python3 python3-dev python3-pip

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Configure with CMake
      run: |
        mkdir -p frontend/build
        cd PYTHML/build
        cmake ..

    - name: Build with Make
      run: |
        cd PYTHML/build
        make

    - name: Run Tests
      run: |
        cd PYTHML/build
        ./PYTHML ../test/cases/base.html
