name: Deploy Documentation

on:
  push:
    branches:
      - main  
      - docs/* 
  pull_request:
    branches:
      - main 

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python (or any other environment you need for docs)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install dependencies (for example, MkDocs)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      # Build the documentation
      - name: Build the documentation
        run: mkdocs build  # Adjust this based on your docs tool

      # Deploy the documentation (example with GitHub Pages)
      - name: Deploy documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to the `gh-pages` branch
          folder: site  # The folder containing the generated documentation (adjust if needed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
